[general]
version = "0.2.0"

[problem]
problem_name = "ahcxxx"
objective = "Min"
score_regex = '(?m)^\s*Score\s*=\s*(?P<score>\d+)\s*$'

[test]
start_seed = 0
end_seed = 100
threads = 0
out_dir = "./pahcer"

# ==============================
#         COMPILE STEPS
# ==============================

# Compile the user's program
[[test.compile_steps]]
program = "g++"
args = ["-std=c++20", "./a/main.cpp", "-I", "D:\\atcoder\\ac-library\\"]

# ==============================
#           TEST STEPS
# ==============================

# Run the tester with the user's program
[[test.test_steps]]
program = "cargo"
args = ["run","-r", "--bin", "tester", "../a.exe"]
current_dir = "./tools"
stdin = "./tools/in/{SEED04}.txt"
stdout = "./tools/out/{SEED04}.txt"
stderr = "./tools/err/{SEED04}.txt"
measure_time = true

